security:
    encoders:
        App\Entity\Alumnos:
            algorithm: bcrypt
            cost: 4          

    providers:
        alumnos:
            entity:
                class: 'App\Entity\Alumnos'
                property: 'email'        

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true   
            logout:
                path: app_logout
                target: /login
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator

    access_control:
        - { path: ^/login$, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        
